core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('package/<slug>/', ItemDetailView.as_view(), name='package'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
    ('P', 'Packages')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField('Label', upload_to='path/')

    def __repr__(self):
        return self

    def __str__(self):
        return self.title

    def get_package_url(self):
        return reverse("core:package", kwargs={
            'slug': self.slug
        })

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/navbar.html
{% load cart_template_tags %}
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      
      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Right -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/">
              <span class="clearfix d-none d-sm-inline-block"> Home </span>
            </a>
          </li>
        </ul>

        <!-- Left -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <i class="fas fa-user-circle"></i>
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwa.me%2Fmessage%2FCQKJPRAFGNENK1%3Ffbclid%3DIwAR1m3EXmtpkX4JMOtKmC7MC_xM2amIhSYPsDIbRLL7lYqkSg48szl-RHPAA&h=AT3gHXMTV1xBUeIzbAWvk5L2P85qsQpP-TTigJFTPFUMMiirDo8hT6j-DYNWf1sTTDjyABJpmbPmSI-2aFK_8XXPrOn-RXhwzVQMvUu5h9UOC6wgq8MRKB4WbT_ntZZpg6cQGA">
            <i class="fas fa-info"></i>
            <span class="clearfix d-none d-sm-inline-block">
              Support
            </span>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <i class="fas fa-user-circle"></i>
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/nonsense.html
{% for item in object_list %}
<!-- <div class="col-lg-4 col-md-3 mb-4">
  
              <div class="card">
  
                <div class="view overlay">
                  {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"> class="card-img-top" {% endcomment %}
                  <img src="https://kamdora.com/wp-content/uploads/2018/09/how-to-prepare-Nigerian-fried-rice.jpg" class="card-img-top">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
  
                <div class="card-body text-center">
                  <!-- <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a> -->
<!-- <h5>
                    <strong>
                      <a href="{{ item.get_absolute_url }}" class="dark-grey-text">Fried Rice
                        <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
</a>
</strong>
</h5>

<h4 class="font-weight-bold" style="color: #b20b0b;">
    <strong>$1.75
    </strong>
</h4>

</div>

</div>

</div> --> -->
{% endfor %}

<!-- {% for item in object_list %}
            <div class="col-lg-4 col-md-3 mb-4">
  
              <div class="card">
  
                <div class="view overlay">
                  {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"> class="card-img-top" {% endcomment %}
                  <img src="https://images.pexels.com/photos/5410422/pexels-photo-5410422.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img-top">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
  
                <div class="card-body text-center">
                  <!-- <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a> -->
<h5>
    <strong>
        <a href="{{ item.get_absolute_url }}" class="dark-grey-text">Stew
            <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
        </a>
    </strong>
</h5>

<h4 class="font-weight-bold" style="color: #b20b0b;">
    <strong>$2
    </strong>
</h4>

</div>

</div>

</div>
{% endfor %} -->



{% for item in object_list %}
<!-- <div class="col-lg-4 col-md-3 mb-4">
  
              <div class="card">
  
                <div class="view overlay">
                  {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"> class="card-img-top" {% endcomment %}
                  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX3VYI5OHNtHb3-13HVPMqAMp1eqp_eie0qQ&usqp=CAU" class="card-img-top">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
  
                <div class="card-body text-center">
                  <!-- <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a> -->
<!-- <h5>
                    <strong>
                      <a href="{{ item.get_absolute_url }}" class="dark-grey-text">Yam Pottage
                        <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
<!-- </a>
                    </strong>
                  </h5>
  
                  <h4 class="font-weight-bold" style="color: #b20b0b;">
                    <strong>$1.90
                    </strong>
                  </h4>
  
                </div>
  
              </div>
  
            </div> --> --> -->
{% endfor %}

{% for item in object_list %}
<!-- <div class="col-lg-4 col-md-3 mb-4">
  
              <div class="card">
  
                <div class="view overlay">
                  {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"> class="card-img-top" {% endcomment %}
                  <img src="https://potofsoups.com/wp-content/uploads/2020/07/egusi-soup.jpg" class="card-img-top">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
  
                <div class="card-body text-center">
                  <!-- <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a> -->
<!-- <h5>
                    <strong>
                      <a href="{{ item.get_absolute_url }}" class="dark-grey-text">Egusi Soup
                        <span class="badge badge-pill {{ item.get_label_display }}" style="background-color: #b20b0b;">NEW</span>
                      </a>
                    </strong>
                  </h5>
  
                  <h4 class="font-weight-bold" style="color: #b20b0b;">
                    <strong>$2.10
                    </strong>
                  </h4>
  
                </div>
  
              </div>
  
            </div> --> -->
{% endfor %}

<!-- {% for item in object_list %}
            <div class="col-lg-4 col-md-3 mb-4">
  
              <div class="card">
  
                <div class="view overlay">
                  {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"> class="card-img-top" {% endcomment %}
                  <img src="http://img.youtube.com/vi/psu9Xyt-rEQ/0.jpg" class="card-img-top">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
  
                <div class="card-body text-center">
                  <!-- <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a> -->
<!-- <h5>
                    <strong>
                      <a href="{{ item.get_absolute_url }}" class="dark-grey-text">Vegetable Soup
                        <span class="badge badge-pill {{ item.get_label_display }}" style="background-color: #b20b0b;">NEW</span>
                      </a>
                    </strong>
                  </h5>
  
                  <h4 class="font-weight-bold" style="color: #b20b0b;">
                    <strong>$1.80
                    </strong>
                  </h4>
  
                </div>
  
              </div>
  
            </div> -->
{% endfor %} -->

<div class="contaoner-fluid">
  <div class="row">
    <div class="col-xs-6">
      <img src="{% static 'img/bg-image' %}" style="float: left;" alt="...">
    </div>
  
    <div class="col-xs-6">
      <h6>WHY CHOOSE VALORES</h6>
  
      <img src="{% static 'img/affor.png' %}">
            <h1 class="mb-4"
              style="font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji; font-size: 1.2rem; font-weight: 500;">
              <strong>Affordable healthy meals for you</strong>
            </h1>
            <p class="text-left"
              style="font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji; font-size: 0.9rem; font-weight: 300;">
              <strong>Spend less for more value on grocery of all your favorite meals. Every package is
                complete, carefully and selectively rationed to meet your nutritional needs.
              </strong>
            </p>
  
            <img src="{% static 'img/hassle.png' %}">
            <h1 class="mb-4"
              style="font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji; font-size: 1.2rem; font-weight: 500;">
              <strong>Hassle-free and safe grocery shopping experiences</strong>
            </h1>
  
            <p class="text-justify"
              style="font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji; font-size: 0.9rem; font-weight: 300;">
              <strong>Shop for groceries-per-meal with ease, and seamless payment experience from your home,
                work-place or school. Free and fast delivery!
              </strong>
            </p>
  
            <img src="{% static 'img/grocery.png' %}">
            <h1 class="mb-4"
              style="font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji; font-size: 1.2rem; font-weight: 500;">
              <strong>Grocery wastes and lost savings</strong>
            </h1>
  
            <p class="text-justify"
              style="font-family: Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji; font-size: 0.9rem; font-weight: 300;">
              <strong>Cease excessively spending on food items, eventually ending up in the bins without consumption.
                Save money, get value!
              </strong>
            </p>
            
    </div>
  </div>
  
</div>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-danger badge-pill">{{ order.items.count }}</span>
    </h4>

    <ul class="list-group mb-3 z-depth-1">

        {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
                </div>
                <span class="text-muted">N{{ order_item.get_final_price }}</span>
            </li>
        {% endfor %}

        {% if order.coupon %}
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
                </div>
                <span class="text-success">-N{{ order.coupon.amount }}</span>
            </li>
        {% endif %}

            <li class="list-group-item d-flex justify-content-between">
                <span>Total (NGN)</span>
                <strong>N{{ order.get_total }}</strong> 
                <!-- <strong>${{ order_item.quantity }} </strong> -->
            </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
        <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
                {{ couponform.code }}
                <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
    <br /> <br />
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order_item.item.title }}</td>
                <td>{{ order_item.item.price }}</td>
                <td>
                    <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                    {{ order_item.quantity }}
                    <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                </td>
                <td>
                {% if order_item.item.discount_price %}
                    N{{ order_item.get_total_discount_item_price }}
                    <span class="badge badge-primary">Saving {{ order_item.item.discount_price }}</span>
                    <!-- <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span> -->
                {% else %}
                    <!-- ${{ order_item.get_total_item_price }} -->
                    N{{ order_item.get_total_item_price }}
                {% endif %}
                <a style='color: #b20b0b;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                    <i class="fas fa-trash float-right"></i>
                </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='5'>Your cart is empty</td>
            </tr>
            <tr>
                <td colspan="5">
                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                </td>
            </tr>
        {% endfor %}

        {% if object.coupon %}
            <tr>
                <td colspan="4"><b>Coupon</b></td>
                <td><b>-N{{ object.coupon.amount }}</b></td>
            </tr>
        {% endif %}

        {% if object.get_total %}
            <tr>
                <td colspan="4"><b>Order Total</b></td>
                <td><b>N{{ object.get_total }}</b></td>
            </tr>
            <tr>
                <td colspan="5">
                <a class='btn float-right ml-2' style="background-color: #b20b0b; color: #fff;" href='/checkout/'>Proceed to checkout</a>
                <a class='btn btn-primary float-right' style="color: #fff;" href='/'>Continue shopping</a>
                </td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/package.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="{{ object.image.url }}" class="img-fluid" alt="">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                <span class="badge mr-1" style="background-color: #b20b0b;">{{ object.title }}</span>
              </a>
            </div>

            <div>
              <a href="{{ item.get_absolute_url }}">
                <!-- <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                <span class="badge purple mr-1">{{ object.title }}</span> -->
                <ol>
                  <li>Abeg</li>
                </ol>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>${{ object.price }}</del>
                </span>
                <span>${{ object.discount_price }}</span>
              {% else %}
               <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>
            
            <!-- <p>
              <small>[Fish / Beef / Chicken / Turkey]</small>
            </p> -->

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
    <script>
    </script>
  </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="{{ object.image.url }}" class="img-fluid" alt="">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <!-- <span class="badge purple mr-1">{{ object.get_category_display }}</span> -->
                <span class="badge mr-1" style="background-color: #b20b0b;">{{ object.title }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>N{{ object.price }}</del>
                </span>
                <span>N{{ object.discount_price }}</span>
              {% else %}
               <span>N{{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>
            
            <!-- <p>
              <small>[Fish / Beef / Chicken / Turkey]</small>
            </p> -->

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
    <script>
    </script>
  </main>

{% endblock content %}